# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Deconvolute mixed haplotypes, and reporting the mixture proportions from each sample
#' This function provieds an interface for calling \emph{dEploid} from R.
#' The command line options are passed via the \code{args} argument.
#'
#' @section blahblah:
#' Blah blah
#'
#' @param args A string containing the command line arguments from scrm.
#'
#' @return A named list of something something ...
#'
#' @export
#'
#' @examples
#' set.seed(1234)
#'
dEploid <- function(args, file = "") {
    .Call('DEploid_dEploid', PACKAGE = 'DEploid', args, file)
}

